[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vtx-protocol"
version = "1.2.6"
description = "WIT definitions and Python bindings for VTX plugins"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "wasmtime>=19.0.0"
]

[tool.setuptools.package-data]
vtx_protocol = ["wit/*.wit", "generated/*.py"]