[package]
name = "vtx-protocol"
version = "1.2.6"
description = "Official WIT interface definitions for VTX Project"
license = "Apache-2.0"
edition = "2021"
include = ["src/**/*", "wit/**/*"]

[lib]
path = "src/lib.rs"