[package]
name = "vtx-protocol"
version = "1.2.3"
description = "The official WIT interface definitions for VTX plugins"
license = "Apache-2.0"
edition = "2021"
include = ["src/**/*", "wit/**/*"]

[lib]
path = "src/lib.rs"