[package]
name = "vtx-protocol"
version = "1.2.6"
description = "The official WIT interface definitions for VTX plugins"
license = "Apache-2.0"
edition = "2021"
include = ["src/**/*", "wit/**/*"]

[lib]
path = "src/lib.rs"

[dependencies]
wit-bindgen = { version = "0.25.0", default-features = false, optional = true }

[features]
default = ["guest"]
guest = ["dep:wit-bindgen", "wit-bindgen/realloc", "wit-bindgen/macros"]
host = ["dep:wit-bindgen"]