name: CI

on:
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]

env:
  CARGO_TERM_COLOR: always

jobs:
  wit-syntax:
    name: Check WIT Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-tools
        uses: bytecodealliance/actions/wasm-tools/setup@v1
      - name: Verify Syntax
        run: make verify-wit

  check-rust:
    name: Test Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: packages/rust
      - name: Run Tests
        run: make test-rust

  check-npm:
    name: Test NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/npm/package-lock.json
      - name: Run Tests
        working-directory: packages/npm
        run: |
          mkdir -p wit
          cp ../../wit/vtx.wit wit/

          npm ci
          npm test

  check-python:
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Tests
        run: make test-python

  check-go:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: packages/go/go.mod
      - name: Run Tests
        run: make test-go

  check-java:
    name: Test Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Tests
        run: make test-java